name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build QA version
        if: github.ref == 'refs/heads/master'
        run: ./gradlew assembleQa
        
      - name: Run detekt
        if: github.event.pull_request
        run: ./gradlew detekt

      - name: Build QA and Production and Development versions for PR
        if: github.event.pull_request
        run: ./gradlew assembleQa assembleProduction assembleDevelopment

